(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Afternoon Seidel, Welcome to Coot version 0.9.8.3")
(use-graphics-interface-state)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good afternoon Seidel. Welcome to Coot 0.9.8.3")
(set-display-lists-for-maps 1)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.pdb" 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz" "/reciprocalspaceship/reciprocalspaceship/F-model" "/reciprocalspaceship/reciprocalspaceship/PHIF-model" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(graphics-molecule-bond-type 0)
(close-molecule 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz" "/reciprocalspaceship/reciprocalspaceship/F-model" "/reciprocalspaceship/reciprocalspaceship/PHIF-model" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 3)
(close-molecule 2)
(close-molecule 0)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.pdb" 1)
(graphics-molecule-bond-type 4)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 5)
(close-molecule 6)
(close-molecule 4)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.pdb" 1)
(graphics-molecule-bond-type 7)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 8)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.ccp4" 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 9)
(close-molecule 10)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 11)
(close-molecule 12)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 13)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 14)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 15)
(close-molecule 16)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 17)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(set-contour-level-in-sigma 1.00)
(set-contour-level-in-sigma 1.00)
(set-contour-level-in-sigma 1.00)
(close-molecule 18)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 19)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz" "/reciprocalspaceship/reciprocalspaceship/F-model" "/reciprocalspaceship/reciprocalspaceship/PHIF-model" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(graphics-general-key-press-hook 65289)
(graphics-molecule-bond-type 7)
(close-molecule 20)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 21)
(close-molecule 22)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 23)
(close-molecule 7)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test2.pdb" 1)
(graphics-molecule-bond-type 24)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 25)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 26)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 27)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.ccp4" 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.pdb" 1)
(graphics-molecule-bond-type 29)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz" "/reciprocalspaceship/reciprocalspaceship/F-model" "/reciprocalspaceship/reciprocalspaceship/PHIF-model" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(close-molecule 28)
(close-molecule 30)
(close-molecule 24)
(close-molecule 29)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.pdb" 1)
(graphics-molecule-bond-type 31)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz" "/reciprocalspaceship/reciprocalspaceship/F-model" "/reciprocalspaceship/reciprocalspaceship/PHIF-model" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(close-molecule 32)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 33)
(close-molecule 34)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 35)
(close-molecule 36)
(close-molecule 31)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_85/Alvra_BT_01-2025_refine_85.pdb" 1)
(graphics-molecule-bond-type 37)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_75/Alvra_BT_01-2025_refine_75.pdb" 1)
(graphics-molecule-bond-type 38)
(close-molecule 37)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_75/Alvra_BT_01-2025_refine_75.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 0.00 0.00)
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_75/Alvra_BT_01-2025_refine_75.mtz" "FOFCWT" "PHFOFCWT" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 0.00 0.00)
(set-go-to-atom-molecule 38)
(update-go-to-atom-window-on-other-molecule-chosen)
(set-go-to-atom-molecule 38)
(update-go-to-atom-window-on-other-molecule-chosen)
(set-go-to-atom-molecule 38)
(update-go-to-atom-window-on-other-molecule-chosen)
(first-coords-imol)
(first-coords-imol)
(graphics-molecule-bond-type 41)
(copy-molecule 38)
(first-coords-imol)
(first-coords-imol)
(copy-molecule 38)
(graphics-molecule-bond-type 38)
(graphics-molecule-bond-type 41)
(graphics-molecule-bond-type 42)
(close-molecule 42)
(first-coords-imol)
(first-coords-imol)
(apply-undo)
(apply-undo)
(first-coords-imol)
(first-coords-imol)
(graphics-molecule-bond-type 43)
(copy-molecule 38)
(close-molecule 38)
(close-molecule 41)
(close-molecule 43)
(close-molecule 39)
(close-molecule 40)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.pdb" 1)
(graphics-molecule-bond-type 44)
(filter-fileselection-filenames-state)
(first-coords-imol)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz" "/reciprocalspaceship/reciprocalspaceship/F-model" "/reciprocalspaceship/reciprocalspaceship/PHIF-model" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(close-molecule 45)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 47)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 48)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 49)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 50)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/maps_scale_screen/test_0.20092330025650468.ccp4")
(set-contour-level-in-sigma 1.00)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/maps_scale_screen/test_0.30538555088334157.ccp4")
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 51)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 52)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(set-contour-level-in-sigma 0.50)
(set-contour-level-in-sigma 0.50)
(close-molecule 46)
(close-molecule 53)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_2.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_2.mtz" "/reciprocalspaceship/reciprocalspaceship/F" "/reciprocalspaceship/reciprocalspaceship/PHI" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_2.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_2.mtz" "/reciprocalspaceship/reciprocalspaceship/F" "/reciprocalspaceship/reciprocalspaceship/PHI" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(close-molecule 54)
(close-molecule 55)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_2.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_2.mtz" "/reciprocalspaceship/reciprocalspaceship/F" "/reciprocalspaceship/reciprocalspaceship/PHI" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 56)
(close-molecule 57)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(close-molecule 58)
(close-molecule 59)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_direct_summation.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_direct_summation.mtz" "/reciprocalspaceship/reciprocalspaceship/F" "/reciprocalspaceship/reciprocalspaceship/PHI" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(close-molecule 60)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_direct_summation.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_direct_summation.mtz" "/reciprocalspaceship/reciprocalspaceship/F" "/reciprocalspaceship/reciprocalspaceship/PHI" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_cctbx.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_cctbx.mtz" "/reciprocalspaceship/reciprocalspaceship/F-model" "/reciprocalspaceship/reciprocalspaceship/PHIF-model" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(set-contour-level-absolute 2.00)
(set-contour-level-absolute 2.00)
(close-molecule 61)
(close-molecule 62)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_cctbx.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_cctbx.mtz" "/reciprocalspaceship/reciprocalspaceship/F-model" "/reciprocalspaceship/reciprocalspaceship/PHIF-model" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_direct_summation.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_direct_summation.mtz" "/reciprocalspaceship/reciprocalspaceship/F" "/reciprocalspaceship/reciprocalspaceship/PHI" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(set-contour-level-in-sigma 1.00)
(close-molecule 63)
(close-molecule 64)
(close-molecule 44)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/dark.pdb" 1)
(graphics-molecule-bond-type 65)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/tubulin.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/tubulin.mtz" "/reciprocalspaceship/reciprocalspaceship/F" "/reciprocalspaceship/reciprocalspaceship/PHI" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(command-in-path-or-absolute? *probe-command*)
(get-show-symmetry)
(set-show-symmetry-master 1)
(get-show-unit-cell 65)
(set-show-unit-cells-all 1)
(set-show-unit-cells-all 1)
(set-show-symmetry-master 1)
(set-show-symmetry-master 1)
(set-show-unit-cells-all 1)
(set-symmetry-atom-labels-expanded 0)
(get-show-symmetry)
(set-show-symmetry-master 1)
(get-show-unit-cell 65)
(set-show-unit-cells-all 1)
(set-show-unit-cells-all 1)
(set-show-symmetry-master 1)
(set-show-symmetry-master 1)
(set-show-unit-cells-all 1)
(set-symmetry-atom-labels-expanded 0)
(get-show-symmetry)
(set-show-symmetry-master 1)
(get-show-unit-cell 65)
(set-show-unit-cells-all 1)
(set-show-unit-cells-all 1)
(set-show-symmetry-master 1)
(set-show-unit-cells-all 1)
(set-symmetry-atom-labels-expanded 0)
(close-molecule 66)
(close-molecule 65)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Ultrafast_tubulin_data/fcalc_diff/files/pdbs/combined.pdb" 1)
(graphics-molecule-bond-type 67)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Ultrafast_tubulin_data/fcalc_diff/files/output/dark_activation_1.mtz")
(close-molecule 67)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_direct_summation.mtz" 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/dark.pdb" 1)
(graphics-molecule-bond-type 68)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/tubulin.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/tubulin.mtz" "/reciprocalspaceship/reciprocalspaceship/F" "/reciprocalspaceship/reciprocalspaceship/PHI" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(set-colour-by-molecule 68)
(graphics-to-b-factor-representation 68)
(graphics-molecule-bond-type 68)
(close-molecule 69)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/tubulin_ds.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/tubulin_ds.mtz" "/reciprocalspaceship/reciprocalspaceship/F" "/reciprocalspaceship/reciprocalspaceship/PHI" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(graphics-molecule-bond-type 68)
(close-molecule 70)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/tubulin_ds.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/tubulin_ds.mtz" "/reciprocalspaceship/reciprocalspaceship/F" "/reciprocalspaceship/reciprocalspaceship/PHI" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(close-molecule 71)
(close-molecule 68)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_85/Alvra_BT_01-2025_refine_85.pdb" 1)
(graphics-molecule-bond-type 72)
(close-molecule 72)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17489/Peter/2025-01-31_SwissFEL_SFX/extrapolation/screen_activaiton_level/xtrapolate_loosened_restraints/3p5ps_5uJ_0/3p5ps_5uJ_0/qweight_occupancy_0.510/3p5ps_5uJ_0_occ0.510_2mqFextr_calc-DFc_reciprocal_space_001_real_space_refined_000.pdb" 1)
(graphics-molecule-bond-type 73)
(filter-fileselection-filenames-state)
(first-coords-imol)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_75/Alvra_BT_01-2025_refine_75.pdb" 1)
(graphics-molecule-bond-type 73)
(graphics-molecule-bond-type 74)
(close-molecule 73)
(close-molecule 74)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_all.pdb" 1)
(graphics-molecule-bond-type 75)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_all.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_all.mtz" "/reciprocalspaceship/reciprocalspaceship/F-model" "/reciprocalspaceship/reciprocalspaceship/PHIF-model" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(close-molecule 76)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_all.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_all.mtz" "/reciprocalspaceship/reciprocalspaceship/F-model" "/reciprocalspaceship/reciprocalspaceship/PHIF-model" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(close-molecule 77)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_85/Alvra_BT_01-2025_refine_85.pdb" 1)
(graphics-molecule-bond-type 75)
(graphics-molecule-bond-type 78)
(close-molecule 75)
(close-molecule 78)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_88/Alvra_BT_01-2025_refine_88.pdb" 1)
(graphics-molecule-bond-type 79)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_88/Alvra_BT_01-2025_refine_88.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 0.00 0.00)
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_88/Alvra_BT_01-2025_refine_88.mtz" "FOFCWT" "PHFOFCWT" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 0.00 0.00)
(close-molecule 79)
(close-molecule 81)
(close-molecule 80)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_aligned_copies.pdb" 1)
(graphics-molecule-bond-type 82)
(close-molecule 82)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_88/Alvra_BT_01-2025_refine_88.pdb" 1)
(graphics-molecule-bond-type 83)
(setup-edit-chi-angles 1)
(setup-edit-chi-angles 0)
(set-show-chi-angle-bond 0)
(set-show-chi-angle-bond 0)
(setup-edit-chi-angles 1)
(setup-edit-chi-angles 0)
(set-show-chi-angle-bond 0)
(set-show-chi-angle-bond 0)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_88/Alvra_BT_01-2025_refine_88.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 0.00 0.00)
(make-and-draw-map-with-reso-with-refmac-params "/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_88/Alvra_BT_01-2025_refine_88.mtz" "FOFCWT" "PHFOFCWT" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 0.00 0.00)
(filter-fileselection-filenames-state)
(first-coords-imol)
(set-add-alt-conf-split-type-number 1)
(setup-edit-chi-angles 1)
(setup-edit-chi-angles 0)
(set-show-chi-angle-bond 0)
(set-show-chi-angle-bond 0)
(setup-edit-chi-angles 1)
(setup-edit-chi-angles 0)
(set-show-chi-angle-bond 0)
(set-show-chi-angle-bond 0)
(set-add-alt-conf-split-type-number 1)
(setup-edit-chi-angles 1)
(setup-edit-chi-angles 0)
(set-show-chi-angle-bond 0)
(set-show-chi-angle-bond 0)
(first-coords-imol)
(first-unsaved-coords-imol)
(close-molecule 84)
(close-molecule 85)
(close-molecule 83)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_88/Alvra_BT_01-2025_refine_88.mtz" 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_89/Alvra_BT_01-2025_refine_89.pdb" 1)
(graphics-molecule-bond-type 86)
(close-molecule 86)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_aligned_copies_1.pdb" 1)
(graphics-molecule-bond-type 87)
