filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Afternoon Seidel, Welcome to Coot version 0.9.8.3")
use_graphics_interface_state ()
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good afternoon Seidel. Welcome to Coot 0.9.8.3")
set_display_lists_for_maps (1)
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.pdb", 1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz", "/reciprocalspaceship/reciprocalspaceship/F-model", "/reciprocalspaceship/reciprocalspaceship/PHIF-model", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
graphics_molecule_bond_type (0)
close_molecule (1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz", "/reciprocalspaceship/reciprocalspaceship/F-model", "/reciprocalspaceship/reciprocalspaceship/PHIF-model", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (3)
close_molecule (2)
close_molecule (0)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.pdb", 1)
graphics_molecule_bond_type (4)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (5)
close_molecule (6)
close_molecule (4)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.pdb", 1)
graphics_molecule_bond_type (7)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (8)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.ccp4", 1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (9)
close_molecule (10)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (11)
close_molecule (12)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (13)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (14)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (15)
close_molecule (16)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (17)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
set_contour_level_in_sigma (1.00)
set_contour_level_in_sigma (1.00)
set_contour_level_in_sigma (1.00)
close_molecule (18)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (19)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz", "/reciprocalspaceship/reciprocalspaceship/F-model", "/reciprocalspaceship/reciprocalspaceship/PHIF-model", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
;; # DIRECT SCHEME ((graphics-general-key-press-hook 65289))
graphics_molecule_bond_type (7)
close_molecule (20)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (21)
close_molecule (22)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (23)
close_molecule (7)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test2.pdb", 1)
graphics_molecule_bond_type (24)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (25)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (26)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (27)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.ccp4", 1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.pdb", 1)
graphics_molecule_bond_type (29)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz", "/reciprocalspaceship/reciprocalspaceship/F-model", "/reciprocalspaceship/reciprocalspaceship/PHIF-model", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
close_molecule (28)
close_molecule (30)
close_molecule (24)
close_molecule (29)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.pdb", 1)
graphics_molecule_bond_type (31)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz", "/reciprocalspaceship/reciprocalspaceship/F-model", "/reciprocalspaceship/reciprocalspaceship/PHIF-model", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
close_molecule (32)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (33)
close_molecule (34)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (35)
close_molecule (36)
close_molecule (31)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_85/Alvra_BT_01-2025_refine_85.pdb", 1)
graphics_molecule_bond_type (37)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_75/Alvra_BT_01-2025_refine_75.pdb", 1)
graphics_molecule_bond_type (38)
close_molecule (37)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_75/Alvra_BT_01-2025_refine_75.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, 0.00, 0.00)
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_75/Alvra_BT_01-2025_refine_75.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, 0.00, 0.00)
set_go_to_atom_molecule (38)
update_go_to_atom_window_on_other_molecule_chosen ()
set_go_to_atom_molecule (38)
update_go_to_atom_window_on_other_molecule_chosen ()
set_go_to_atom_molecule (38)
update_go_to_atom_window_on_other_molecule_chosen ()
first_coords_imol ()
first_coords_imol ()
graphics_molecule_bond_type (41)
copy_molecule (38)
first_coords_imol ()
first_coords_imol ()
copy_molecule (38)
graphics_molecule_bond_type (38)
graphics_molecule_bond_type (41)
graphics_molecule_bond_type (42)
close_molecule (42)
first_coords_imol ()
first_coords_imol ()
apply_undo ()
apply_undo ()
first_coords_imol ()
first_coords_imol ()
graphics_molecule_bond_type (43)
copy_molecule (38)
close_molecule (38)
close_molecule (41)
close_molecule (43)
close_molecule (39)
close_molecule (40)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.pdb", 1)
graphics_molecule_bond_type (44)
filter_fileselection_filenames_state ()
first_coords_imol ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test.mtz", "/reciprocalspaceship/reciprocalspaceship/F-model", "/reciprocalspaceship/reciprocalspaceship/PHIF-model", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
close_molecule (45)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (47)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (48)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (49)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (50)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/maps_scale_screen/test_0.20092330025650468.ccp4")
set_contour_level_in_sigma (1.00)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/maps_scale_screen/test_0.30538555088334157.ccp4")
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (51)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (52)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
set_contour_level_in_sigma (0.50)
set_contour_level_in_sigma (0.50)
close_molecule (46)
close_molecule (53)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_2.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_2.mtz", "/reciprocalspaceship/reciprocalspaceship/F", "/reciprocalspaceship/reciprocalspaceship/PHI", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_2.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_2.mtz", "/reciprocalspaceship/reciprocalspaceship/F", "/reciprocalspaceship/reciprocalspaceship/PHI", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
close_molecule (54)
close_molecule (55)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_2.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_2.mtz", "/reciprocalspaceship/reciprocalspaceship/F", "/reciprocalspaceship/reciprocalspaceship/PHI", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (56)
close_molecule (57)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
close_molecule (58)
close_molecule (59)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_direct_summation.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_direct_summation.mtz", "/reciprocalspaceship/reciprocalspaceship/F", "/reciprocalspaceship/reciprocalspaceship/PHI", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
close_molecule (60)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_direct_summation.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_direct_summation.mtz", "/reciprocalspaceship/reciprocalspaceship/F", "/reciprocalspaceship/reciprocalspaceship/PHI", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_cctbx.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_cctbx.mtz", "/reciprocalspaceship/reciprocalspaceship/F-model", "/reciprocalspaceship/reciprocalspaceship/PHIF-model", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
set_contour_level_absolute (2.00)
set_contour_level_absolute (2.00)
close_molecule (61)
close_molecule (62)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_cctbx.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_cctbx.mtz", "/reciprocalspaceship/reciprocalspaceship/F-model", "/reciprocalspaceship/reciprocalspaceship/PHIF-model", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_direct_summation.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_direct_summation.mtz", "/reciprocalspaceship/reciprocalspaceship/F", "/reciprocalspaceship/reciprocalspaceship/PHI", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
set_contour_level_in_sigma (1.00)
close_molecule (63)
close_molecule (64)
close_molecule (44)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/dark.pdb", 1)
graphics_molecule_bond_type (65)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/tubulin.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/tubulin.mtz", "/reciprocalspaceship/reciprocalspaceship/F", "/reciprocalspaceship/reciprocalspaceship/PHI", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
;; # DIRECT SCHEME ((command-in-path-or-absolute? *probe-command*))
get_show_symmetry ()
set_show_symmetry_master (1)
get_show_unit_cell (65)
set_show_unit_cells_all (1)
set_show_unit_cells_all (1)
set_show_symmetry_master (1)
set_show_symmetry_master (1)
set_show_unit_cells_all (1)
set_symmetry_atom_labels_expanded (0)
get_show_symmetry ()
set_show_symmetry_master (1)
get_show_unit_cell (65)
set_show_unit_cells_all (1)
set_show_unit_cells_all (1)
set_show_symmetry_master (1)
set_show_symmetry_master (1)
set_show_unit_cells_all (1)
set_symmetry_atom_labels_expanded (0)
get_show_symmetry ()
set_show_symmetry_master (1)
get_show_unit_cell (65)
set_show_unit_cells_all (1)
set_show_unit_cells_all (1)
set_show_symmetry_master (1)
set_show_unit_cells_all (1)
set_symmetry_atom_labels_expanded (0)
close_molecule (66)
close_molecule (65)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Ultrafast_tubulin_data/fcalc_diff/files/pdbs/combined.pdb", 1)
graphics_molecule_bond_type (67)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Ultrafast_tubulin_data/fcalc_diff/files/output/dark_activation_1.mtz")
close_molecule (67)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_direct_summation.mtz", 1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/dark.pdb", 1)
graphics_molecule_bond_type (68)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/tubulin.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/tubulin.mtz", "/reciprocalspaceship/reciprocalspaceship/F", "/reciprocalspaceship/reciprocalspaceship/PHI", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
set_colour_by_molecule (68)
graphics_to_b_factor_representation (68)
graphics_molecule_bond_type (68)
close_molecule (69)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/tubulin_ds.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/tubulin_ds.mtz", "/reciprocalspaceship/reciprocalspaceship/F", "/reciprocalspaceship/reciprocalspaceship/PHI", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
graphics_molecule_bond_type (68)
close_molecule (70)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/tubulin_ds.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/tubulin_ds.mtz", "/reciprocalspaceship/reciprocalspaceship/F", "/reciprocalspaceship/reciprocalspaceship/PHI", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
close_molecule (71)
close_molecule (68)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_85/Alvra_BT_01-2025_refine_85.pdb", 1)
graphics_molecule_bond_type (72)
close_molecule (72)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17489/Peter/2025-01-31_SwissFEL_SFX/extrapolation/screen_activaiton_level/xtrapolate_loosened_restraints/3p5ps_5uJ_0/3p5ps_5uJ_0/qweight_occupancy_0.510/3p5ps_5uJ_0_occ0.510_2mqFextr_calc-DFc_reciprocal_space_001_real_space_refined_000.pdb", 1)
graphics_molecule_bond_type (73)
filter_fileselection_filenames_state ()
first_coords_imol ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_75/Alvra_BT_01-2025_refine_75.pdb", 1)
graphics_molecule_bond_type (73)
graphics_molecule_bond_type (74)
close_molecule (73)
close_molecule (74)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_all.pdb", 1)
graphics_molecule_bond_type (75)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_all.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_all.mtz", "/reciprocalspaceship/reciprocalspaceship/F-model", "/reciprocalspaceship/reciprocalspaceship/PHIF-model", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
close_molecule (76)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_all.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_all.mtz", "/reciprocalspaceship/reciprocalspaceship/F-model", "/reciprocalspaceship/reciprocalspaceship/PHIF-model", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
close_molecule (77)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_85/Alvra_BT_01-2025_refine_85.pdb", 1)
graphics_molecule_bond_type (75)
graphics_molecule_bond_type (78)
close_molecule (75)
close_molecule (78)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_88/Alvra_BT_01-2025_refine_88.pdb", 1)
graphics_molecule_bond_type (79)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_88/Alvra_BT_01-2025_refine_88.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, 0.00, 0.00)
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_88/Alvra_BT_01-2025_refine_88.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, 0.00, 0.00)
close_molecule (79)
close_molecule (81)
close_molecule (80)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_aligned_copies.pdb", 1)
graphics_molecule_bond_type (82)
close_molecule (82)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_88/Alvra_BT_01-2025_refine_88.pdb", 1)
graphics_molecule_bond_type (83)
setup_edit_chi_angles (1)
setup_edit_chi_angles (0)
set_show_chi_angle_bond (0)
set_show_chi_angle_bond (0)
setup_edit_chi_angles (1)
setup_edit_chi_angles (0)
set_show_chi_angle_bond (0)
set_show_chi_angle_bond (0)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_88/Alvra_BT_01-2025_refine_88.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, 0.00, 0.00)
make_and_draw_map_with_reso_with_refmac_params ("/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_88/Alvra_BT_01-2025_refine_88.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, 0.00, 0.00)
filter_fileselection_filenames_state ()
first_coords_imol ()
set_add_alt_conf_split_type_number (1)
setup_edit_chi_angles (1)
setup_edit_chi_angles (0)
set_show_chi_angle_bond (0)
set_show_chi_angle_bond (0)
setup_edit_chi_angles (1)
setup_edit_chi_angles (0)
set_show_chi_angle_bond (0)
set_show_chi_angle_bond (0)
set_add_alt_conf_split_type_number (1)
setup_edit_chi_angles (1)
setup_edit_chi_angles (0)
set_show_chi_angle_bond (0)
set_show_chi_angle_bond (0)
first_coords_imol ()
first_unsaved_coords_imol ()
close_molecule (84)
close_molecule (85)
close_molecule (83)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_88/Alvra_BT_01-2025_refine_88.mtz", 1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Alvra_BT_01_2025/Refine_89/Alvra_BT_01-2025_refine_89.pdb", 1)
graphics_molecule_bond_type (86)
close_molecule (86)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/das/work/p17/p17490/Peter/Library/multicopy_refinement/test_data/test_aligned_copies_1.pdb", 1)
graphics_molecule_bond_type (87)
